INSERT INTO TB_CARGO(TX_NOME) VALUES('GERENTE');
INSERT INTO TB_CARGO(TX_NOME) VALUES('SUPERVISOR');
INSERT INTO TB_CARGO(TX_NOME) VALUES('AUXILIAR');
INSERT INTO TB_CARGO(TX_NOME) VALUES('OPERADOR');
INSERT INTO TB_CARGO(TX_NOME) VALUES('MAQUINISTA');

INSERT INTO TB_ATIVIDADE(TX_NOME) VALUES('ATIVIDADE 1');
INSERT INTO TB_ATIVIDADE(TX_NOME) VALUES('ATIVIDADE 2');
INSERT INTO TB_ATIVIDADE(TX_NOME) VALUES('ATIVIDADE 3');
INSERT INTO TB_ATIVIDADE(TX_NOME) VALUES('ATIVIDADE 4');
INSERT INTO TB_ATIVIDADE(TX_NOME) VALUES('ATIVIDADE 5');

INSERT INTO TB_EQUIPAMENTO(TX_NOME,NU_CERTIFICADO_APROVACAO) VALUES('Calçado de segurança',9356);
INSERT INTO TB_EQUIPAMENTO(TX_NOME,NU_CERTIFICADO_APROVACAO) VALUES('Capacete de segurança',9357);
INSERT INTO TB_EQUIPAMENTO(TX_NOME,NU_CERTIFICADO_APROVACAO) VALUES('Luvas de segurança',9357);
